### ISSUE TITLE
Support for file upload

### ISSUE THREAD

**Issue by sammyrulez** [GabrielCappelli/openapi-specgen#3]
Support for file upload https://swagger.io/docs/specification/describing-request-body/file-upload/

**Comment by GabrielCappelli** [comment]
We can use the same solution as proposed here.

https://github.com/GabrielCappelli/openapi-specgen/issues/4

**Comment by sammyrulez** [comment]
I think it would be great.
Actually _format_ is not writable, I was thinking to monkey patch is but if you  add format direct support it would be great.

**Comment by GabrielCappelli** [comment]
Expected way to do this in 1.0.0 is using a custom type and a custom resolver.
