### ISSUE TITLE
String parameter format

### ISSUE THREAD

**Issue by TomerRZN** [GabrielCappelli/openapi-specgen#4]
Did i miss a way to create an OpenApiParam and describing its format (or any other schema property)?

**Comment by GabrielCappelli** [comment]
If you pass an object that's a Dataclass or contains a Marshmallow Schema in attribute `__marshmallow__` it'll be able to identify it and generate the schema.

```python
from dataclasses import dataclass
from openapi_specgen import OpenApiParam
@dataclass
class Foo():
    bar: str

param = OpenApiParam('test_param', 'query', Foo)
param.as_dict() 

# Generated output for this OpenApiParam 
#{'required': True, 'name': 'test_param', 'in': 'query', 'schema': {'$ref': '#/components/schemas/Foo', 'title': 'Test_Param'}}
```

**Comment by TomerRZN** [comment]
I do understand that this is how you generate schema for various objects, however this is not the case i was talking about.
I want to describe a param's properties in the case it isn't an object.
Few examples (In yaml since i took them from website):


A string parameter with a format of uuid
`
        - in: header
          name: X-Request-ID
          schema:
            type: string
            **format: uuid**
          required: true
`

An integer parameter whose value is an enum:
`
        - in: cookie
          name: debug
          schema:
            type: integer
            **enum: [0, 1]**
`

An integer parameter with minimum value:
`
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
            default: 0
          required: false
`

**Comment by GabrielCappelli** [comment]
Oh, sorry, I misunderstood.

Currently format is supported only by type. Meaning specific types have specific formats (date and datetime).

We can add a optional parameter `format`, if specified it'll be set as the format in the schema for that param.

Does that work for you ?

**Comment by GabrielCappelli** [comment]
Expected way to do this in 1.0.0 is using a custom type and a custom resolver.
