### ISSUE TITLE
list[str] type in dataclass is not handled correctly

### ISSUE THREAD

**Issue by Huge** [GabrielCappelli/openapi-specgen#6]
With

```
@dataclass
class DC:
    report_list: list[str] 
```
we obtain 
```      'LemoneroStartCompanyScoring': {
        'title': 'LemoneroStartCompanyScoring',
        'required': [
          report_list'
        ],
        'type': 'object',
        'properties': {
          'report_list': {
            '$ref': '#/components/schemas/list'
          }
```
which seems wrong.

**Comment by Huge** [comment]
Making the type `    scoring_report_list: List[str] ` imported from typing helps, which is good news, yet still..

**Comment by GabrielCappelli** [comment]
Hey, this lib was written and tested in Python 3.7 and this syntax `list[str]` was not yet available.

Python has added many improvements to the type hinting system since then, but this lib would need to be updated to be compatible with those.

**Comment by Huge** [comment]
I did not actually expect any reply and your explanation is well informative to me @GabrielCappelli! 

Any estimate, what would be a [motivating bounty](https://app.bountysource.com/issues/116036432-list-str-type-in-dataclass-is-not-handled-correctly) for updating? (the bounty page can be considered provisional)

Similar issue that comes with an illegible error:
```
@dataclass
class Evaluator:
    actions: Dict[str, Any]
```

Edit: adding provisional patch:
```
Index: lib/python3.10/site-packages/openapi_specgen/schema.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/python3.10/site-packages/openapi_specgen/schema.py b/lib/python3.10/site-packages/openapi_specgen/schema.py
--- a/lib/python3.10/site-packages/openapi_specgen/schema.py	
+++ b/lib/python3.10/site-packages/openapi_specgen/schema.py	(date 1674218908556)
@@ -73,6 +73,10 @@
     '''
     openapi_type = get_openapi_type(data_type)
     if openapi_type == 'object':
+        import typing
+        # if type(data_type) is type and type(data_type.type) is typing._SpecialGenericAlias:
+        if type(data_type) is typing._GenericAlias or type(data_type) is typing._SpecialGenericAlias:
+            return {}
         if issubclass(data_type, marshmallow.Schema):
             return get_openapi_schema_from_mashmallow_schema(data_type, reference=reference)
         if reference:

**Comment by GabrielCappelli** [comment]
> Any estimate, what would be a [motivating bounty](https://app.bountysource.com/issues/116036432-list-str-type-in-dataclass-is-not-handled-correctly) for updating? (the bounty page can be considered provisional)

This is really up to you and not at all necessary. 

I'm working full time and will not be able to dedicate a lot of time to this, that being said I will have a look at it tomorrow

**Comment by GabrielCappelli** [comment]
@Huge with version [1.0.0](https://github.com/GabrielCappelli/openapi-specgen/pull/7)  any annotated Sequence types (list, tuple, etc) and any annotated Mapping types (dict, defaultdict, etc) should work correctly.
